spring:
  application:
    name: accounts
  profiles:
    active: production
  main:
    allow-bean-definition-overriding: true

# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

application:
  allow-get-accounts: ${spring.allow-get-accounts}

eureka:
  client: ${eureka-client}